services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: prueba_laravel58_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    networks:
      - test_net

  web:
    image: nginx:alpine
    container_name: prueba_laravel58_web
    restart: unless-stopped
    ports:
      - "8058:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - test_net

networks:
  test_net:
    driver: bridge
